### ISSUE TITLE
SubscriptionManager crash loop

### ISSUE THREAD

**Issue by Glagnar** [ScorpioBroker/ScorpioBroker#104]
The following crash occurs after starting the project via. docker after a couple of minutes.

```
[[30m2020-08-20T12:39:07,494^[[m ^[[33mWARN  ^[[m[^[[1;34mmain^[[m] ^[[1;33mo.s.c.s.AbstractApplicationContext^[[m: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notificationController': Unsatisfied dependency expressed through field 'subscriptionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'subscriptionService': Unsatisfied dependency expressed through field 'kafkaTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eu.neclab.ngsildbroker.commons.stream.service.KafkaConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'query.result.topic' in value "${query.result.topic}"
^[[30m2020-08-20T12:39:07,535^[[m ^[[32mINFO  ^[[m[^[[1;34mmain^[[m] ^[[1;33mo.s.s.c.ExecutorConfigurationSupport^[[m: Shutting down ExecutorService 'taskScheduler'
^[[30m2020-08-20T12:39:07,664^[[m ^[[32mINFO  ^[[m[^[[1;34mmain^[[m] ^[[1;33mo.a.j.l.DirectJDKLog^[[m: Stopping service [Tomcat]
^[[30m2020-08-20T12:39:08,036^[[m ^[[32mINFO  ^[[m[^[[1;34mmain^[[m] ^[[1;33mo.s.b.a.l.ConditionEvaluationReportLoggingListener^[[m:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
^[[30m2020-08-20T12:39:08,131^[[m ^[[1;31mERROR ^[[m[^[[1;34mmain^[[m] ^[[1;33mo.s.b.SpringApplication^[[m: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notificationController': Unsatisfied dependency expressed through field 'subscriptionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'subscriptionService': Unsatisfied dependency expressed through field 'kafkaTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eu.neclab.ngsildbroker.commons.stream.service.KafkaConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'query.result.topic' in value "${query.result.topic}"
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
```

**Comment by ScorpioBroker** [comment]
Hi,
sorry for the inconvenience. Dev and testing of that change were done with the all in one runner so i missed that. I'll update our testing as well for this.
i've hotfixed the docker container for the subscription manager for latest and 0.9.11.
PR for the hotfix into dev is on it's way. 
I'll leave this open till the fix is in dev.
BR
Benjamin
