### ISSUE TITLE
Postgres Connection Attempt Failed

### ISSUE THREAD

**Issue by StWiemann** [ScorpioBroker/ScorpioBroker#196]
Hi there, I would like to test ScorpioBroker. But so far I had no success to deploy it onto a small kubernetes test-cluster with 5 nodes.
I am using the Rancher-UI for most stuff. 
Deployment is aaio, postgres seems to accept other connections (tested with grafana) but scorpio won't start with a bunch of warnings and an error when it comes to database connection.

Scorpio-Config:

image: scorpiobroker/scorpio:scorpio-aaio_1.0.5
published container port: 9090:9090 ClusterIP (Internal only)
ENV:
```spring_args: --bootstrap.servers=kafka-cluster.kafka.svc.cluster.local:9092 --reader.datasource.hikari.password=PASSWORD --reader.datasource.hikari.url=jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/ngb?ApplicationName=ngb_storagemanager_reader --reader.datasource.hikari.username=postgres --writer.datasource.hikari.password=PASSWORD --writer.datasource.hikari.url=jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/ngb?ApplicationName=ngb_storagemanager_writer --writer.datasource.hikari.username=postgres```

Spring seems to have issues starting up since the log shows the logo 4 times before progressing.

I will try to shorten the very verbose log to keep information relevant. The whole log is attached.
[scorpio.log](https://github.com/ScorpioBroker/ScorpioBroker/files/5951457/scorpio.log)

Log:
```
...
WARN 138 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
...
WARN 138 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
...
WARN 138 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
...
2021-02-09 12:44:11.139  WARN 138 --- [           main] o.a.k.clients.consumer.ConsumerConfig    : The configuration 'spring.json.trusted.packages' was supplied but isn't a known config.
2021-02-09 12:44:11.143  INFO 138 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version : 2.0.1
2021-02-09 12:44:11.143  INFO 138 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId : fa14705e51bd2ce5
2021-02-09 12:44:11.341  INFO 138 --- [           main] org.apache.kafka.clients.Metadata        : Cluster ID: 6H_3mXesQTuyNMu4ZoPOXw
2021-02-09 12:44:11.342  INFO 138 --- [           main] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] Discovered group coordinator kafka-cluster.kafka.svc.cluster.local:9092 (id: 2147482646 rack: null)
2021-02-09 12:44:11.346  INFO 138 --- [           main] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] Revoking previously assigned partitions []
2021-02-09 12:44:11.346  INFO 138 --- [           main] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] (Re-)joining group
2021-02-09 12:44:11.363  INFO 138 --- [           main] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] Successfully joined group with generation 1
2021-02-09 12:44:11.365  INFO 138 --- [           main] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] Setting newly assigned partitions [ATCONTEXT-0]
2021-02-09 12:44:11.378  INFO 138 --- [           main] o.a.k.c.consumer.internals.Fetcher       : [Consumer clientId=consumer-1, groupId=de16d1a7-89d2-4659-85f7-74bf2e30be03] Resetting offset for partition ATCONTEXT-0 to offset 0.
2021-02-09 12:44:11.716  INFO 138 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 5.2.4 by Boxfuse
2021-02-09 12:44:11.727  INFO 138 --- [           main] com.zaxxer.hikari.HikariDataSource       : SpringBootHikariCP_Reader - Starting...
2021-02-09 12:44:12.807 ERROR 138 --- [           main] com.zaxxer.hikari.pool.HikariPool        : SpringBootHikariCP_Reader - Exception during pool initialization.
org.postgresql.util.PSQLException: The connection attempt failed.

...

Caused by: java.net.UnknownHostException: postgres
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at org.postgresql.core.PGStream.<init>(PGStream.java:75) ~[postgresql-42.2.8.jar!/:42.2.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91) ~[postgresql-42.2.8.jar!/:42.2.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192) ~[postgresql-42.2.8.jar!/:42.2.8]
	... 70 common frames omitted
2021-02-09 12:44:12.811  WARN 138 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityService': Unsatisfied dependency expressed through field 'storageWriterDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'emstorage': Unsatisfied dependency expressed through field 'writerJdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database: The connection attempt failed.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.
2021-02-09 12:44:12.811  INFO 138 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2021-02-09 12:44:12.819  INFO 138 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-02-09 12:44:12.840  INFO 138 --- [           main] ConditionEvaluationReportLoggingListener :
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-02-09 12:44:12.845 ERROR 138 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityService': Unsatisfied dependency expressed through field 'storageWriterDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'emstorage': Unsatisfied dependency expressed through field 'writerJdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database: The connection attempt failed.
-------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : The connection attempt failed.

```

Maybe I'm missing something? Is the way to define the environmentals correct? I assumed it is, since the log shows the right kafka-endpoint. Help with this would be much appreciated, since I've been trying for a few weeks on and off again now.

**Comment by arpitNEC** [comment]
hello @StWiemann,
Just for confirmation have you deployed the Postgres, zookeeper, and Kafka deployment as well as their services before deploying the Scorpio Broker and in the following order.
If not then please follow the steps:-
1. deploy PV and PVC file for Postgres(https://github.com/ScorpioBroker/ScorpioBroker/blob/development/KubernetesFile/aaio-deployment-files/pv%20and%20storages/postgres-storage.yaml)
2. Deploy the Postgres file(https://github.com/ScorpioBroker/ScorpioBroker/blob/development/KubernetesFile/aaio-deployment-files/deployments/postgres-deployment.yaml)
3. Deploy the Postgres service file(https://github.com/ScorpioBroker/ScorpioBroker/blob/development/KubernetesFile/aaio-deployment-files/services/postgres-service.yaml)
4. Deploy the zookeeper deployment.
5. Deploy the zookeeper Service.
6. Deploy the Kafka PV(https://github.com/ScorpioBroker/ScorpioBroker/blob/development/KubernetesFile/aaio-deployment-files/pv%20and%20storages/kafka-pv.yaml)
7. Deploy the Kafka PVC(https://github.com/ScorpioBroker/ScorpioBroker/blob/development/KubernetesFile/aaio-deployment-files/pv%20and%20storages/kafka-claim0-persistentvolumeclaim.yaml)
8. Deploy the Kafka deployment(**Note:** make sure that the Kafka deployment is up and running before deploying the Kafka service as it sometimes creates error) 
9. Deploy the Kafka service.
10. Deploy the Scorpio Broker aaio deployment and the required services (Cluster IP or node port).(can use helm file as well)
After that, if the problem is not resolved then please update me with the error.

**Comment by ScorpioBroker** [comment]
Hi,

@StWiemann this is indeed a mess up in our documentation. The parameters are without hikari so e.g. 
writer.datasource.url instead of writer.datasource.hikari.url.

I'll patch the documentation.

**Comment by StWiemann** [comment]
Thank you for the quick response! With changing the URL-env-names and also adding `--spring.cloud.stream.kafka.binder.brokers=kafka-cluster.kafka.svc.cluster.local:9092` it is no longer crashing. I'll have to test it before I can confirm that it runs properly, but so far everything looks fine. Thanks!
