### ISSUE TITLE
Subscription to QuantumLeap

### ISSUE THREAD

**Issue by diego-gv** [ScorpioBroker/ScorpioBroker#227]
Hello,

I am trying to create a subscription in Scopio towards the QuantumLeap to store data (time series) from air quality sensors, but it fails when the subscription is made.

The stack I am using is as follows:

- Postman 
- Scorpio 1.0.5
- QuantumLeap 0.8
- CrateDB 4.1.8
- Grafana 6.7.4

The entity I create is as follows:

```
curl --location --request POST 'http://0.0.0.0:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:AirQualityObserved:001",
    "type": "AirQualityObserved",
    "CO": {
        "type": "Property",
        "value": 313.7300109,
        "description": {
            "type": "Property",
            "value": "CO value"
        },
        "ranges": {
            "type": "Property",
            "value": {
                "good": [
                    0,
                    9999
                ],
                "unhealthyForSensitiveGroups": [
                    10000,
                    29999
                ],
                "unhealthy": [
                    30000,
                    49999
                ],
                "hazardous": [
                    50000,
                    "inf"
                ]
            }
        },
        "unitCode": "GQ",
        "dateObserved": {
            "type": "Property",
            "value": "2021-02-12T09:55:39.00Z"
        }
    },
[...] # more attributes similar to CO
    "location": {
        "type": "GeoProperty",
        "value": {
            "type": "Point",
            "coordinates": [
                -3.70256,
                40.4165
            ]
        }
    },
    "@context": [
        "https://fiware.github.io/data-models/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}'
```

I create the subscription as follows:

```
{
    "description": "Notify me any change in AirQualityObserver entities",
    "type": "Subscription",
    "entities": [
        {
            "type": "AirQualityObserved"
        }
    ],
    "watchedAttributes": [
        "CO"
        "location"
    ],
    "notification": {
        "format": "normalized",
        "endpoint": {
            "uri": "http://quantumleap:8668/v2/notify",
            "accept": "application/json"
        }
    },
    "@context": "https://fiware.github.io/data-models/context.jsonld"
}
```

The entity I update it as follows:

```
curl --location --request PATCH 'http://0.0.0.0:9090/ngsi-ld/v1/entities/urn:ngsi-ld:AirQualityObserved:001/attrs/CO' \
--header 'Content-Type: application/json' \
--data-raw '{
    "value": 305.6105
}'
```

But the quantumleap shows the following in the log:

```
time=2021-06-04 10:45:00.924 | level=ERROR | corr=None | from=172.18.2.1 | srv=None | subserv=None | op=log_exception | comp=server.wsgi | msg=Exception on /v2/notify [POST] | payload=[{'id': 'urn:ngsi-ld:AirQualityObserved:001', 'type': 'https://uri.fiware.org/ns/data-models#AirQualityObserved', 'createdAt': '2021-06-04T10:41:01.997000Z', 'CO': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [30000.0, 49999.0], 'unhealthyForSensitiveGroups': [10000.0, 29999.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 9999.0], 'https://uri.fiware.org/ns/data-models#hazardous': [50000.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'CO value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 305.6105, 'modifiedAt': '2021-06-04T10:45:00.606000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'H2S': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [10000.0, 19999.0], 'unhealthyForSensitiveGroups': [5000.0, 9999.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 4999.0], 'https://uri.fiware.org/ns/data-models#hazardous': [20000.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'H2S value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 4.3099999, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'NO': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [7000.0, 19999.0], 'unhealthyForSensitiveGroups': [2500.0, 6999.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 2499.0], 'https://uri.fiware.org/ns/data-models#hazardous': [20000.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'NO value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 145.8300018, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'NO2': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [560.0, 999.0], 'unhealthyForSensitiveGroups': [200.0, 559.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 199.0], 'https://uri.fiware.org/ns/data-models#hazardous': [1000.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'NO2 value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 37.0400009, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'O3': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [240.0, 299.0], 'unhealthyForSensitiveGroups': [120.0, 239.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 119.0], 'https://uri.fiware.org/ns/data-models#hazardous': [300.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'O3 value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 28.1000003, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'SO2': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'ranges': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'unhealthy': [1000.0, 1999.0], 'unhealthyForSensitiveGroups': [350.0, 999.0], 'https://uri.fiware.org/ns/data-models#good': [0.0, 349.0], 'https://uri.fiware.org/ns/data-models#hazardous': [2000.0, 'inf']}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'S02 value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 6.69, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'VOC': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'description': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': 'VOC value', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'value': 9.034089, 'modifiedAt': '2021-06-04T10:41:01.997000Z', 'https://uri.fiware.org/ns/data-models#dateObserved': {'type': 'Property', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': '2021-02-12T09:55:39.00Z', 'modifiedAt': '2021-06-04T10:41:01.997000Z'}}, 'location': {'type': 'GeoProperty', 'createdAt': '2021-06-04T10:41:01.997000Z', 'value': {'type': 'Point', 'coordinates': [-3.70256, 40.4165]}, 'modifiedAt': '2021-06-04T10:41:01.997000Z'}, 'modifiedAt': '2021-06-04T10:45:00.606000Z'}] | thread=140653264603936  | process=40
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 153, in notify
    error = _validate_payload(entity)
  File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 102, in _validate_payload
    if not has_value(payload, attr):
  File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 60, in has_value
    attr_value = attr.get('value', None)
AttributeError: 'str' object has no attribute 'get'
```

Any idea?

I have tried several versions of subscription (`normalized`, `keyValues`, without indicating all attributes in `watchedAttributes`, with `watchedAttributes` empty) but I get the feeling that Scorpio is not yet compatible with Quantumleap.

Best regards.

**Comment by diego-gv** [comment]
Hello, the problem persists. Thank you.

**Comment by ScorpioBroker** [comment]
Hi,

unfortunately none of us has used QuantumLeap so i can't really help you here. it seems like a bug in quantumleap to me at the moment. When i get some time i'll check our notification output to make sure we are not producing something wrong here.

**Comment by amitrnec** [comment]
Hi,

Please check "http://quantumleap:8668/v2/notify"notification endpoint that is provided in subscription request. I think this endpoint related to ngsi-v2 version so need to validate by QuantumLeap team.

Thanks.

**Comment by diego-gv** [comment]
Hi, 

I have tried different subscription variations, but I can only get QuantumLeap to create the metadata table in the CrateDB.

The conclusion I come to is that there is still a lack of either compatibility with QuantumLeap or maturity of QuantumLeap with NGSI-LD.

Best regards,
