### ISSUE TITLE
The scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.13 fails if Notification subscription has filter

### ISSUE THREAD

**Issue by ccndukwe** [ScorpioBroker/ScorpioBroker#324]
Below is the notification payload

{
    "description": "Notify QuantumLeap on changes on water quality data",
    "id": "urn:subscription:10",
    "type": "Subscription",
    "entities": [
        {
            "type": "Device"
        }
    ],
    "q":"type==Device",
    "notification": {
        "format": "keyValues",
        "endpoint": {
            "uri": "https://eojuakb8u1r6aug.m.pipedream.net",
            "accept": "application/json"
        }
    }
}

Below is the log of the error

Exception in thread "Thread-2224" java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.List (java.util.LinkedHashMap$Entry and java.util.List are in module java.base of loader 'bootstrap')
        at eu.neclab.ngsildbroker.commons.tools.SerializationTools.parseRelationship(SerializationTools.java:260)
        at eu.neclab.ngsildbroker.commons.tools.EntityTools.getBaseProperties(EntityTools.java:120)
        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService.generateDataFromBaseOp(BaseSubscriptionService.java:527)
        at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService$2.run(BaseSubscriptionService.java:475)
Exception in thread "Thread-2225" java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.List (java.util.LinkedHashMap$Entry and java.util.List are in module java.base of loader 'bootstrap')

**Comment by ScorpioBroker** [comment]
Hi could you please provide a payload example for your entity which should trigger. 
Which Scorpio version are you running?
I can't recreate your exception at the moment.
It's a bug for sure but aside from that your subscription is a bit weird. 
The entities part is already filtering for type Device only.
So the type==Device is not needed. But it's stopping your subscription from working as you would expect because in q queries you can only check on attributes (so. property, geoproperty, relationship). it would not check the entity type like this but start looking for a property/relationship called type (which you are not allowed to create).

BR

**Comment by ccndukwe** [comment]
The problem is the version and not the payload,  I tried all kinds of query and they all failed. The version is shown in the title which is scorpio:scorpio-aaio-no-eureka_2.1.13. However, I decided to use another version and it worked.

**Comment by ScorpioBroker** [comment]
Ok than this was most likely fixed in between. Latest is currently 2.1.20 or you can always use latest 

BR
