### ISSUE TITLE
Question: How to enable ssl for postgres connection 

### ISSUE THREAD

**Issue by yshashix** [ScorpioBroker/ScorpioBroker#348]
Is their SSL connection to Postgres DB, if not how do you enable it? I would like to know for the quarkus java release.

**Comment by ScorpioBroker** [comment]
Hi,
we haven't been using SSL on the DB until now. There is SSL support for the database connectors but to be honest never used it. I'll investigate a bit how to use it.

**Comment by yshashix** [comment]
I guess by default scorpio is using reactive postgressql and  I need to set this parameters [quarkus.datasource.reactive.postgresql.ssl-mode = require]. I guess pgpool option for SSL handling at source code is not enabled. Is it right?

**Comment by MericFeyz** [comment]
Hi @ScorpioBroker, I have been trying to come up with a solution for this since my Postgres configuration rejects non ssl connections but I am unsuccessful so far. I have tried configuring the PgConnectOptions in the ClientManager class of the "eu.neclab.ngsildbroker.commons.storage" package by appending ```setSsl(true).setTrustAll(true)``` to the existing configuration per the [vertx docs](https://vertx.io/docs/vertx-pg-client/java/#_using_ssltls). However that couldn't solve the error I get. Following is the error message: 

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-10-28 10:36:35,131 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 8.5.10 by Redgate
2022-10-28 10:36:35,392 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.10
2022-10-28 10:36:35,392 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
2022-10-28 10:36:37,078 INFO  [org.fly.cor.int.dat.bas.BaseDatabaseType] (main) Database: jdbc:postgresql://acid-cluster:5432/ngb (PostgreSQL 12.8)
2022-10-28 10:36:37,271 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 20220311.1
2022-10-28 10:36:37,276 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
2022-10-28 10:36:37,291 INFO  [io.qua.sma.ope.run.OpenApiRecorder] (main) Default CORS properties will be used, please use 'quarkus.http.cors' properties instead
2022-10-28 10:36:37,638 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2022-10-28 10:36:37,829 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup (total:0 started:0)
2022-10-28 10:36:37,829 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.14.1 (camel-1) started in 65ms (build:0ms init:61ms start:4ms)
2022-10-28 10:36:40,790 ERROR [io.sma.rea.mes.provider] (main) SRMSG00212: Unable to initialize mediator: eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingInMemory#handleInternalNotification: java.lang.RuntimeException: Error injecting eu.neclab.ngsildbroker.subscriptionmanager.service.SubscriptionService eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingBase.subscriptionService
        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingInMemory_Bean.create(Unknown Source)
        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingInMemory_Bean.create(Unknown Source)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:111)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:32)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:32)
        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingInMemory_Bean.get(Unknown Source)
        at eu.neclab.ngsildbroker.subscriptionmanager.messaging.SubscriptionMessagingInMemory_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:467)
        at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:480)
        at io.quarkus.arc.impl.BeanManagerImpl.getReference(BeanManagerImpl.java:59)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager.createMediator(MediatorManager.java:162)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.createMediator(Unknown Source)
        at io.smallrye.reactive.messaging.providers.wiring.Wiring$SubscriberMediatorComponent.materialize(Wiring.java:571)
        at io.smallrye.reactive.messaging.providers.wiring.Graph.lambda$materialize$10(Graph.java:100)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at io.smallrye.reactive.messaging.providers.wiring.Graph.materialize(Graph.java:99)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager.start(MediatorManager.java:205)
        at io.smallrye.reactive.messaging.providers.extension.MediatorManager_ClientProxy.start(Unknown Source)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:41)
        at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_7f54e4b27c1b49e5e062caa58f1e82797fa01393.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:323)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:305)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:73)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:130)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:99)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
Caused by: io.vertx.pgclient.PgException: FATAL: pg_hba.conf rejects connection for host "10.42.1.24", user "ngb", database "ngb", SSL off (28000)
        at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
        at io.vertx.pgclient.impl.codec.InitCommandCodec.handleErrorResponse(InitCommandCodec.java:100)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:132)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-10-28 10:36:40,811 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.14.1 (camel-1) shutting down (timeout:45s)
2022-10-28 10:36:40,818 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (total:0 stopped:0)
2022-10-28 10:36:40,872 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.14.1 (camel-1) shutdown in 61ms (uptime:3s47ms)
2022-10-28 10:36:40,993 ERROR [io.qua.run.Application] (main) Failed to start application (with profile in-memory): io.vertx.pgclient.PgException: FATAL: pg_hba.conf rejects connection for host "10.42.1.24", user "ngb", database "ngb", SSL off (28000)
        at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
        at io.vertx.pgclient.impl.codec.InitCommandCodec.handleErrorResponse(InitCommandCodec.java:100)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:132)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

```
Your codebase is massive and it might be that I am missing some other classes that handle the database connections. Please let me know if so. For the record the program started correctly when I tried to disable the ssl requirement from my postgres service.

Best regards
