### ISSUE TITLE
Notifications when connection closed causing SocketException

### ISSUE THREAD

**Issue by steveaitch** [ScorpioBroker/ScorpioBroker#355]
I have a notification set up to deliver to an AWS API Gateway endpoint. However, after a time the idle HTTP connection is closed by the other side (or a load balancer) but Apache HTTP Client doesn't handle this situation silently and instead throws an exception when the next notification tries and writes to the socket, so the notification is lost:

	2022-11-04 08:55:07.234 ERROR 8 --- [pool-7-thread-1] e.n.n.c.s.NotificationHandlerREST        : Exception ::
	java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[na:na]
	...
	at org.apache.http.client.fluent.Request.internalExecute(Request.java:173) ~[httpclient-osgi-4.5.13.jar!/:4.5.13]
	at org.apache.http.client.fluent.Request.execute(Request.java:177) ~[httpclient-osgi-4.5.13.jar!/:4.5.13]
	at eu.neclab.ngsildbroker.commons.subscriptionbase.NotificationHandlerREST.sendReply(NotificationHandlerREST.java:87) ~[Commons-1.1.0-SNAPSHOT.jar!/:na]
	at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseNotificationHandler.notify(BaseNotificationHandler.java:80) ~[Commons-1.1.0-SNAPSHOT.jar!/:na]
	at eu.neclab.ngsildbroker.commons.subscriptionbase.BaseSubscriptionService.sendNotification(BaseSubscriptionService.java:522)

NotificationHandlerREST ought to deal with this situation. I would be inclined to treat every SocketException as retryable.

**Comment by amitrnec** [comment]
Hi,
Now this issue has been fixed #364 

Thanks,
Amit.
