### ISSUE TITLE
Failed to create SSL connection (Link header)

### ISSUE THREAD

**Issue by vgonzalez7** [ScorpioBroker/ScorpioBroker#493]
Hello,

I am using the latest version (_scorpiobroker/all-in-one-runner:java-kafka-4.1.11_) and I ran into an issue when including the Link header in my requests.

For instance, if I request:
```
GET /ngsi-ld/v1/entities?type=AgriParcel 
Accept: application/ld+json
Link: <https://raw.githubusercontent.com/smart-data-models/dataModel.Agrifood/master/context.jsonld>;rel="http://www.w3.org/ns/json-ld#context";type="application/ld+json"
```

I get as a response:
```
{
    "type": "https://uri.etsi.org/ngsi-ld/errors/LdContextNotAvailable",
    "title": "LD context not available.",
    "detail": {
        "message": "LD context not available."
    },
    "errorCode": 503
}
```

But if I use the long type name in the request (_https://smartdatamodels.org/dataModel.Agrifood/AgriParcel_) and no Link header, the response is as expected (200 OK and an Entity batch).

The docker logs show the following:
```
javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
        at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:127)
2023-12-12 11:22:49,906 WARNING [com.git.ben.caf.cac.LocalAsyncCache] (vert.x-eventloop-thread-22) Exception thrown during asynchronous load: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
        at io.vertx.core.net.impl.ChannelProvider$1.userEventTriggered(ChannelProvider.java:127)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:400)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:376)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:368)
        at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443)
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2217)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2213)
        ... 10 more
 
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:400)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:376)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:368)
        at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:443)
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2217)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
        at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2213)
        ... 10 more
```

If I perform a curl from inside the Scorpio docker, it works just fine, like:
```
Request:
$ curl https://raw.githubusercontent.com/smart-data-models/dataModel.Agrifood/master/context.jsonld

Response:
{
    "@context": {
       ...
    }
}
```

So it doesn't look like a connection problem, but rather something internal happening in the broker.
I have also tried to set the env variable ATCONTEXT_URL in the docker compose like so:
```
ATCONTEXT_URL: http://localhost:9090/ngsi-ld/v1/jsonldContexts/
```

But the result is the same.

Thanks for your time.
Víctor

**Comment by amitrnec** [comment]
Hi,
We are not able to reproduce this error.
It is working as expected in our system. Might be this error in your side due to some network restriction.

Thanks.
