### ISSUE TITLE
Quarkus failed start when using java kafka > 4.1.4

### ISSUE THREAD

**Issue by mathias-vh** [ScorpioBroker/ScorpioBroker#551]
When using a version later then 4.1.4, I am unable to get scorpio to work using the kafka version.

I noticed that after version 4.1.4 and onwards, the deserializer and serializer values are commented out in the application.kafka properties. 
See below:
_mp.messaging.incoming.registryretrieve.connector=smallrye-kafka
mp.messaging.incoming.registryretrieve.topic=${scorpio.topics.registry}
mp.messaging.incoming.registryretrieve.auto.offset.reset=latest
**#mp.messaging.incoming.registryretrieve.value.deserializer=eu.neclab.ngsildbroker.commons.serialization.messaging.BaseRequestDeserializer**
mp.messaging.incoming.registryretrieve.broadcast=true
mp.messaging.outgoing.registry.topic=${scorpio.topics.registry}
mp.messaging.outgoing.registry.connector=smallrye-kafka
**#mp.messaging.outgoing.registry.value.serializer=eu.neclab.ngsildbroker.commons.serialization.messaging.BaseRequestSerializer**_

When uncommenting the deserializer and serializer values , i receive the  following error:

Configured topics for channel 'subaliveretrieve': [context-staging-subalive]
2024-04-22T13:10:25.688492969Z 2024-04-22 13:10:25,687 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18214: Key deserializer omitted, using String as default
2024-04-22T13:10:25.756700645Z 2024-04-22 13:10:25,747 ERROR [io.sma.rea.mes.provider] (main) SRMSG00230: Unable to create the publisher or subscriber during initialization: java.lang.IllegalArgumentException: SRMSG18010: Unable to create an instance of `eu.neclab.ngsildbroker.commons.serialization.messaging.AliveAnnouncementDeserializer`
2024-04-22T13:10:25.756745144Z 	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:64)
2024-04-22T13:10:25.756780544Z 	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.<init>(DeserializerWrapper.java:35)
...
 Caused by: java.lang.ClassNotFoundException: eu.neclab.ngsildbroker.commons.serialization.messaging.AliveAnnouncementDeserializer
2024-04-22T13:10:26.500364267Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2024-04-22T13:10:26.500367767Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2024-04-22T13:10:26.500371367Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2024-04-22T13:10:26.500454666Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
2024-04-22T13:10:26.500459366Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
2024-04-22T13:10:26.500463266Z 	at java.base/java.lang.Class.forName0(Native Method)
2024-04-22T13:10:26.500474666Z 	at java.base/java.lang.Class.forName(Class.java:467)
2024-04-22T13:10:26.500478566Z 	at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:422)
2024-04-22T13:10:26.500482166Z 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:411)
2024-04-22T13:10:26.500487266Z 	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.createDelegateDeserializer(DeserializerWrapper.java:62)

**Comment by ScorpioBroker** [comment]
Hi,

yes this is correct we removed them in favor of more general to String serialization because of the different message buses we are supporting now. These two don't exist anymore. We will remove the commented lines.
